spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scaffold?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: geejay
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 20
        min-idle: 0
        max-active: 50
        max-wait: 30000
    connect-timeout: 3000