spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scaffold?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: geejay
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 20
        min-idle: 0
        max-active: 50
        max-wait: 30000
    connect-timeout: 3000
  rabbitmq:
    host: localhost
    port: 5672
    username: geejaywoo
    password: geejaywoo
    listener:
      simple:
#       3次重试后失败 丢弃消息
        default-requeue-rejected: true
        retry:
          enabled: true
          initial-interval: 3000ms
          max-attempts: 3
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
application:
  mq:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics, threaddump